export const fallbackProperties = [
  {
    id: 'demo-1',
    title: 'Pearl Heights Furnished Apartment',
    city: 'Kampala',
    district: 'Kololo',
    region: 'central',
    price: 2400000,
    currency: 'UGX',
    propertyType: 'APARTMENT',
    bedrooms: 2,
    bathrooms: 2,
    description: 'A bright furnished apartment with secure parking, fast routes to the CBD, and reliable utilities.',
    images: [{ url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'WiFi' }, { name: 'Parking' }, { name: 'Security' }],
    landlord: { firstName: 'Amina', lastName: 'Kato', verified: true, verificationBadge: true, phone: '+256700000001' },
    nearbyFacilities: ['Supermarket', 'Clinic', 'Public transport'],
    similar: [],
  },
  {
    id: 'demo-2',
    title: 'Ntinda Family Townhouse',
    city: 'Kampala',
    district: 'Ntinda',
    region: 'central',
    price: 1800000,
    currency: 'UGX',
    propertyType: 'TOWNHOUSE',
    bedrooms: 3,
    bathrooms: 2,
    description: 'A calm townhouse with private compound space, family-friendly rooms, and managed maintenance.',
    images: [{ url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'Water Included' }, { name: 'Parking' }],
    landlord: { firstName: 'Amina', lastName: 'Kato', verified: true, verificationBadge: true, phone: '+256700000001' },
    nearbyFacilities: ['School', 'Gym', 'Pharmacy'],
    similar: [],
  },
  {
    id: 'demo-3',
    title: 'Makerere Student Hostel Suite',
    city: 'Kampala',
    district: 'Makerere',
    region: 'central',
    price: 650000,
    currency: 'UGX',
    propertyType: 'HOSTEL',
    bedrooms: 1,
    bathrooms: 1,
    description: 'A compact hostel suite designed for students who need proximity, safety, and predictable costs.',
    images: [{ url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'Furnished' }, { name: 'WiFi' }],
    landlord: { firstName: 'Amina', lastName: 'Kato', verified: true, verificationBadge: true, phone: '+256700000001' },
    nearbyFacilities: ['Campus', 'Food courts', 'Taxi stage'],
    similar: [],
  },
  {
    id: 'demo-4',
    title: 'Jinja Riverside Studio',
    city: 'Jinja',
    district: 'Jinja city',
    region: 'eastern',
    price: 900000,
    currency: 'UGX',
    propertyType: 'STUDIO',
    bedrooms: 1,
    bathrooms: 1,
    description: 'A neat studio close to the riverfront, town services, restaurants, and transport links.',
    images: [{ url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'WiFi' }, { name: 'Water Included' }],
    landlord: { firstName: 'Grace', lastName: 'Namutebi', verified: true, verificationBadge: true, phone: '+256700000004' },
    nearbyFacilities: ['Riverfront', 'Market', 'Taxi park'],
    similar: [],
  },
  {
    id: 'demo-5',
    title: 'Gulu City Two Bedroom Home',
    city: 'Gulu',
    district: 'Gulu city',
    region: 'northern',
    price: 1100000,
    currency: 'UGX',
    propertyType: 'HOUSE',
    bedrooms: 2,
    bathrooms: 2,
    description: 'A secure two bedroom home with compound space and easy access to Gulu city amenities.',
    images: [{ url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'Parking' }, { name: 'Security' }],
    landlord: { firstName: 'Peter', lastName: 'Odong', verified: true, verificationBadge: false, phone: '+256700000005' },
    nearbyFacilities: ['Hospital', 'School', 'Supermarket'],
    similar: [],
  },
  {
    id: 'demo-6',
    title: 'Mbarara Managed Office Suite',
    city: 'Mbarara',
    district: 'Mbarara city',
    region: 'western',
    price: 1500000,
    currency: 'UGX',
    propertyType: 'OFFICE',
    bedrooms: 0,
    bathrooms: 1,
    description: 'A managed office suite for growing teams with reception access and reliable utilities.',
    images: [{ url: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80' }],
    amenities: [{ name: 'WiFi' }, { name: 'Parking' }, { name: 'Security' }],
    landlord: { firstName: 'Brian', lastName: 'Tumwesigye', verified: true, verificationBadge: true, phone: '+256700000006' },
    nearbyFacilities: ['Banks', 'Restaurants', 'Main road'],
    similar: [],
  },
];
